export const CREATE_ITEM_REQUEST = "CREATE_ITEM_REQUEST";
export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const CREATE_ITEM_FAILURE = "CREATE_ITEM_FAILURE";

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILURE = "DELETE_ITEM_FAILURE";

export const SEARCH_ITEM_REQUEST = "SEARCH_ITEM_REQUEST";
export const SEARCH_ITEM_SUCCESS = "SEARCH_ITEM_SUCCESS";
export const SEARCH_ITEM_FAILURE = "SEARCH_ITEM_FAILURE";

export const UPDATE_ITEMS_AVAILABILITY_REQUEST = "UPDATE_ITEMS_AVAILABILITY_REQUEST";
export const UPDATE_ITEMS_AVAILABILITY_SUCCESS = "UPDATE_ITEMS_AVAILABILITY_SUCCESS";
export const UPDATE_ITEMS_AVAILABILITY_FAILURE = "UPDATE_ITEMS_AVAILABILITY_FAILURE";

export const GET_ALL_ITEMS_REQUEST = "GET_ALL_ITEMS_REQUEST";
export const GET_ALL_ITEMS_SUCCESS = "GET_ALL_ITEMS_SUCCESS";
export const GET_ALL_ITEMS_FAILURE = "GET_ALL_ITEMS_FAILURE";