export const CREATE_FEEDBACK_REQUEST = "CREATE_FEEDBACK_REQUEST";
export const CREATE_FEEDBACK_SUCCESS = "CREATE_FEEDBACK_SUCCESS";
export const CREATE_FEEDBACK_FAILURE = "CREATE_FEEDBACK_FAILURE";

export const DELETE_FEEDBACK_REQUEST = "DELETE_FEEDBACK_REQUEST";
export const DELETE_FEEDBACK_SUCCESS = "DELETE_FEEDBACK_SUCCESS";
export const DELETE_FEEDBACK_FAILURE = "DELETE_FEEDBACK_FAILURE";

export const SEARCH_FEEDBACK_REQUEST = "SEARCH_FEEDBACK_REQUEST";
export const SEARCH_FEEDBACK_SUCCESS = "SEARCH_FEEDBACK_SUCCESS";
export const SEARCH_FEEDBACK_FAILURE = "SEARCH_FEEDBACK_FAILURE";

export const GET_ALL_FEEDBACKS_REQUEST = "GET_ALL_FEEDBACKS_REQUEST";
export const GET_ALL_FEEDBACKS_SUCCESS = "GET_ALL_FEEDBACKS_SUCCESS";
export const GET_ALL_FEEDBACKS_FAILURE = "GET_ALL_FEEDBACKS_FAILURE";